---
toc: true
reference-location: margin
# citation-location: margin
---

# Alaska customization

For our Alaska-centric analysis, we've introduced some not-officially-CEFI-endorsed additions and tweaks to the CEFI Dataset described in the previous section.

- horizontal subset subdomain: `iqX-XjqX-X`, where X's indicate the iq/jq values that bound the subdomain 
- horizontal average subdomain: `ak_surveyregion_avg` for metrics where the horizontal dimensions were collapsed to regional averages based on Alaska survey area polygons [@fig-ak-masks-4].
- grid type: `extra` for variables that fall on the native grid but are not part of the "raw" dataset, e.g. variables added in postprocessing, and also for variables that do not fall on either the native or regridded grids (e.g., regional averages).  I will probably revisit this naming scheme as workflows mature... but it works for now.

## The Alaska subregion of the MOM6-NEP grid

These analyses focus on regions that fall under Alaska management, including the Bering Sea, Aleutian Islands, Gulf of Alaska, and Arctic.^[We do not currently produce any Arctic metrics for the PEEC or ESRs, but we include that region for future possiblities.]  The bounds of these regions cover a bit over a third of the total MOM6 northeast Pacific (NEP) grid.  For much of our Alaska analysis, we will extract only the data from this relevant region.

```{matlab}
%| label: fig-mom6gridmap
%| fig-cap: Map of MOM6-NEP grid with Alaska management polygons.  White transparent polygons indicate the Alaska ESR regions (Bering, Gulf of Alaska, Aleutian Islands, and Arctic) while red polygons indicate the groundfish survey regions for the Northern Bering Sea (NBS), Eastern Bering Sea (EBS), Gulf of Alaska (GOA), and Aleutian Islands (AI).  The navy dashed line indicates the Alaska iq0-342jq446-743 subregion.
%| code-fold: true

addpath('../code')
w = warning('off'); % ignore the polygon warnings...

% Use a static file from the latest release on the Portal to get model grid
 
C = cefiportalopts('region', 'nep', ...
                   'release', 'r20241015', ...
                   'freq', 'monthly'); 

Grd = readcefigridvars(C, {'geolat_c', 'geolon_c', 'deptho'}, 'expandname', false);
[ltlimnep(1), ltlimnep(2)] = bounds(Grd.geolat_c(:));
[lnlimnep(1), lnlimnep(2)] = bounds(wrapTo360(Grd.geolon_c(:)));

% Plot model grid-cell depths

h.fig = figure('color', 'w');
h.fig.Position(3:4) = [800 800];
h.ax = axes;

padh = @(x) [x nan(size(x,1),1); nan(1,size(x,2)+1)];
h.bm = boxworldmap(ltlimnep, lnlimnep, 'pticks', 'r', 'mticks', 'b');
set(gca, 'box', 'on')
h.bathy = pcolorm(Grd.geolat_c, Grd.geolon_c, padh(Grd.deptho));
h.ax.XLim(1) = min(h.bathy.XData(:));

proj = getm(gca);

% Add management shapes
% Mix of projected polyshapes vs geostructures is just for plotting
% purposes) 

S = akshapes;
Esr = geotable2struct(S.esr_regions([1 3 4 2],:));
for ii = 1:length(Esr)
    [x,y] = projfwd(proj, Esr(ii).Lat, Esr(ii).Lon);
    Esr(ii).pshape = polyshape(x,y);
end

Svy = geotable2struct(S.base_layers_survey_area([1:7 11],:));
for ii = 1:length(Svy)
    [Svy(ii).Lat, Svy(ii).Lon] = projinv(projcrs(3338), Svy(ii).X, Svy(ii).Y);
end

h.esr = plot([Esr.pshape], 'facecolor', 'w', 'linewidth', 1.2);
h.svy = plotm([Svy(1:end-1).Lat], [Svy(1:end-1).Lon],  'r');

[ltlim(1), ltlim(2)] = bounds([Esr.Lat]);
[lnlim(1), lnlim(2)] = bounds(wrapTo360([Esr.Lon]));

% Add subregion box

Mask = build_ak_masks(...
    'cpopts', C, ...
    'expandname', false, ....
    'setuponly', true);
subregidx = mask2hyperslab(~isnan(Mask.esr_area.val), "vector");
fprintf("Subregion iq/jq indices based on ESR mask bounds: %d %d %d %d\n", subregidx);

iidx = (subregidx(1):subregidx(2))+1;
jidx = (subregidx(3):subregidx(4))+1;

h.sub(1) = plotm(Grd.geolat_c(iidx,jidx(1  )), Grd.geolon_c(iidx,jidx(1  )));
h.sub(2) = plotm(Grd.geolat_c(iidx,jidx(end)), Grd.geolon_c(iidx,jidx(end)));
h.sub(3) = plotm(Grd.geolat_c(iidx(1  ),jidx), Grd.geolon_c(iidx(1  ),jidx));
h.sub(4) = plotm(Grd.geolat_c(iidx(end),jidx), Grd.geolon_c(iidx(end),jidx));
set(h.sub, 'linestyle', '--', 'linewidth', 1.5, 'color', [0 0.06 0.3]);

% Land border data

[blat, blon] = cellfun(@(x) borders(x), {'canada', 'russia', 'mexico', 'states'},'uni', 0);
blat = [blat(1:3) blat{4}'];
blon = [blon{1:3} blon{4}'];
[bx,by] = cellfun(@(a,b) projfwd(proj,a,b), blat, blon, 'uni', 0);
bps = polyshape(bx,by);

h.cst = plot(bps, 'edgecolor', 'none', 'facecolor', [1 1 1]*0.6, 'facealpha', 1);

% Tweak aesthetics

set(gca, 'colormap', cmocean('deep'), ...
    'clim', [0 8000], ...
    'fontsize', 8);

% Add colorbar

h.cb = colorbar('west');
h.cb.Position(4) = 0.3;
set(h.cb, 'tickdir', 'out', 'fontsize', 8);
xlabel(h.cb, 'Depth (m)');
```


Within local datasets, this subregion is identified as `iq0-342jq446-743`, indicating the indices of the corner grid cells that bound the region.

## Masks for spatially-averaged indices

Our analysis summarizes regional model output across a variety of management-related geometries, often collapsing the 3D and 4D model data to one-dimensional time series by averaging across regions of interest.  These include marine management areas, marine statistical areas, and fishery-independent survey regions in Alaska, as defined via the AFSC GAP program's [akgfmaps R package](https://github.com/afsc-gap-products/akgfmaps). Masks relating these polygons to the MOM6-NEP model grid can be found in the frequency=`static`, grid=`extra` variable collection for the relevant hindcast simulations.

```{matlab}
%| label: fig-ak-masks
%| fig-cap: Alaska-region vector geometries mapped onto the MOM6-NEP grid.
%| fig-subcap: 
%|   - "Alaska Marine Ecosystem Status Reports: Ecosystem Area"
%|   - "Alaska Marine Ecosystem Status Reports: Ecosystem Subarea"
%|   - "ADFG Stat Area"
%|   - "Bottom trawl survey area"
%|   - "Bottom trawl survey strata ID"
%|   - "INPFC Area"
%|   - "Marine Regions of the Bering Sea Shelf and Slope (Bering Sea Integrated Ecosystem Research Program)"
%|   - "Red King Crab survey strata"
%|   - "Blue King Crab survey strata"
%|   - "Snow crab survey strata"
%|   - "Tanner crab survey strata"
%|   - "NMFS Reporting Area (Electronic Code of Federal Regulations, Part 679, Appendix A)"
%| code-fold: true
%| layout-ncol: 2

% Plot masks

cmapbase = [...
            141,211,199
            255,255,179
            190,186,218
            251,128,114
            128,177,211
            253,180,98
            179,222,105
            252,205,229
            217,217,217
            188,128,189]./255; % ColorBrewer pastel

padh = @(x) [x nan(size(x,1),1); nan(1,size(x,2)+1)];

fld = fieldnames(Mask);
for ii = 1:length(fld)
    figure;
    h = boxworldmap(ltlim, lnlim, 'mticks', 't', 'pticks', 'l');

    if ii == 1
        proj = getm(gca);
        [bx,by] = cellfun(@(a,b) projfwd(proj,a,b), blat, blon, 'uni', 0);
        bps = polyshape(bx,by);
    end

    if ismember(fld{ii}, {'adfg_stat_area', 'bsierp_region', 'nmfs_area'})
        x = Mask.(fld{ii}).val;
    else
        [xunq, x, n] = discretemask(Mask.(fld{ii}).val);
    end

    switch fld{ii}
        case 'adfg_stat_area'
            cmap = vivid(cmapbase(1:7,:), 7*20);
            clim = [300000 1000000];
            ctk = 300000:100000:1000000;
            ctklbl = string(ctk);
        case 'survey_strata'
            cmap = vivid(cmapbase, n);
            clim = [0.5 n+0.5];
            ctk = 1:3:n;
            ctklbl = string(xunq(1:3:n));
        case 'bsierp_region'
            n = max(x(:));
            cmap = cmocean('matter', n);
            clim = [0.5 n+0.5];
            ctk = 1:n;
            ctklbl = string(ctk);
        case 'nmfs_area'
            cmap = vivid(cmapbase(1:3,:), 30);
            clim = [400 700];
            ctk = [];
            ctklbl = [];
        otherwise
            cmap = cmapbase(1:n,:);
            clim = [0.5 n+0.5];
            ctk = 1:n;
            ctklbl = string(xunq);
    end

    pcolorm(Grd.geolat_c, Grd.geolon_c, padh(x));
    set(h.ax, 'fontsize', 8, 'colormap', cmap, 'clim', clim);
    plot(bps, 'facecolor', [1 1 1]*0.5, 'edgecolor', 'none');
    h.cb = colorbar('north');
    h.cb.Position(3) = 0.2;
    if ~isempty(ctk)
        set(h.cb, 'ticks', ctk, 'ticklabels', ctklbl);
    end

end

function [xunq, x, n] = discretemask(a)

    [xunq,~,x] = unique(a);
    xunq = xunq(~isnan(xunq));
    x = reshape(x, size(a));
    x(isnan(a)) = NaN;
    n = max(x(:));

end
```

