---
toc: true
reference-location: margin
engine: jupyter-matlab
---

# Spring PEEC 2025

## The simulation

:::{.callout-note}
The text below was written at the time of the Spring 2025 PEEC.  I have left it here for transparency of methods.  However, due to a bug discovered in the forcing of the e202411 simulation, the majority of the plots in the following section have been updated to use the e202507 simulation output that was subsequently run in summer 2025.  This shows what the PEEC predictions would have been without that bug.  We opt not to preserve the bug-affected e202411 version of the plots to avoid future confusion.  This explains any mismatch you may see between the figures here and archived versions of the 2025 Spring PEEC slides.
:::

For this simulation, we used a custom extension of the MOM6-NEP hindcast (r202411) simulation.  This simulation was an "unofficial" variant on the primary MOM6-NEP hindcast (accessible on the CEFI portal), and included a few caveats:

- At the time of the extension, the GLORYS dataset that is used for ocean boundary forcing only extended through 03/25/2025, while the atmospheric forcing from ERA5 extended to 04/12/2025, and the GloFAS river forcing reached 04/16/2025.  For the gap between 03/25 and 4/12, the following method was applied for ocean boundary conditions: 
    1) daily climatology for 1995-2024 as constructed
    2) mean delta added from the last 30 days of available GLORYS obcs relative to the same days in the daily climatology, and 
    3) weighting applied to the the last GLORYS day over 10 days into the into the climatology to smooth the transition.
- The simulation originally used a version of the GloFAS-derived river forcing that unintentionally removed the Columbia River.  This bug was fixed for our extension (since the buggy input files were not retained), hence the Columbia "turns on" in 2024.  We do not expect this to affect the Alaska region.
- The boundary sponges used an older algorithm; while since improved upon, the older method shouldn't be detrimental.

This simulation was run by Liz Drenkard at GFDL on 4/22/2025 and archived on GFDL's PPAN (processing and analysis) cluster.

## Figures for slides

Because this was the first year during which we presented regional model output from the MOM6-NEP model rather than the Bering10K ROMS model, we provided some brief background on the model itself.  See @fig-mom6gridmap for an updated version of the figure presented to show the location of Alaska regions within the MOM6-NEP grid.

We also ran a quick repeat of the persistence forecast skill assessment previously conducted for our Bering10K ROMS model [@Kearney2021c].  We expanded the analysis to the full Alaska region, and also quickly assessed carbonate system variables for predictability.  This was a very quick assessment; a more thorough one (particularly for the carbonate system variables, where in the interest of time we did not separate predictability due to long-term trends from the seasonal persistence signal) is still warranted.

:::{.callout-note}
TODO: need to add this
:::

The core of our presentation expanded on indices presented at previous PEEC meetings for the Bering Sea, but now expanded to all Alaska regions.  We show timeseries of variables spatially averaged over the survey regions, both over time (with summer values highlighted for comparison with survey data) and versus day of year, highlighting the most recent years.  We also plot the spatial anomaly at the final time step of the hindcast (Apr 11, 2025) and the July 1 persistence forecast value attained by overlaying this anomaly on July 1 climatological conditions.

```{matlab}
%| label: fig-peec25-indices-and-maps
%| fig-cap: From right to left-- variable values over time (grey line = daily hindcast values, red line = persistence forecast values, green circles = July 1 values, red circle = July 1 persistence forecast values); variable values versus day of year, highlighting the most recent 4 years with forecast values in the red dashed line; and maps of the (top) spatial anomaly on the last simulated date and (bottom) predicted value based on this anomaly overlaid on July 1 climatological conditions.
%| fig-subcap:
%|   - Bottom temperature
%|   - 2-degree cold pool index (map shows bottom temperature)
%|   - 0-degree cold pool index (map shows bottom temperature)
%|   - Surface temperature
%|   - Bottom oxygen
%| code-fold: true

addpath('../code');

C = cefiportalopts('portalpath', '~/Documents/Data/CEFI/ak_cefiportal/', ...
                   'region', 'nep', ...
                   'release', 'e202507', ...
                   'freq', 'daily', ...
                   'yyyymmdd', '20240101', ...
                   'subdomain', 'iq0-342jq446-743'); 


regnum = [98 143 52 47]; % EBS, NBS, AI, GOA
regname = ["EBS", "NBS", "AI", "GOA"];
reglong = ["Southeast Bering Sea", "Northern Bering Sea", "Aleutian Islands", "Gulf of Alaska"];

% Variable setup: which ones do we plot?

vplt = ["tob", "cpool2p0", "cpool0p0", "tos", "btm_o2"]; %, "pH", "omega"];

% Read surveyavg indices from file

Tbl = readindexdata(C.setopts('subdomain', 'aksvyreg'), ...
    'regnum', regnum, ...
    'vars', vplt);

% Remove leap days from climatology

isleap = month(Tbl.Clim.t) == 2 & day(Tbl.Clim.t) == 29;
Tbl.Clim = Tbl.Clim(~isleap,:);

% Remove post-PEEC-2025 hindcast data (note: this is only necessary since
% we're rerunning the PEEC analysis after an additional summer extension
% was added)

Tbl.Hc = Tbl.Hc(Tbl.Hc.t <= datetime(2025,4,11),:);

% Map setup for anomaly/forecast maps

A = akmapprep('cpopts', C, 'maskvar', 'mask_esr_area', 'maskval', [1 3 4], ...
    'latbuffer', 0.01, 'lonbuffer', 0.01);

nreg = length(regnum);
tilesz = [nreg 5];

tnum = @(r,c) sub2ind(tilesz([2 1]), c, r);

V = ak_variable_info;

% Read map slice data
% TODO: need to handle pH, omega anomalies separately

MapAnom = readmom6mapslice(C, datetime(2025,4,11), ...
    'vars', setdiff(vplt, ["cpool2p0", "cpool0p0"]), 'vartype', 'anomaly');
MapFc = readmom6mapslice(C, datetime(2025,7,1), ...
    'vars', setdiff(vplt, ["cpool2p0", "cpool0p0"]), 'vartype', 'fcpersist');
MapAnom.cpool2p0 = MapAnom.tob;
MapAnom.cpool0p0 = MapAnom.tob;
MapFc.cpool2p0 = MapFc.tob;
MapFc.cpool0p0 = MapFc.tob;

for iv = 1:length(vplt)

    % Figure and tiling setup

    h.fig = figure('color', 'w');
    h.fig.Position(3:4) = [1300 600]; % slide size
    h.t = tiledlayout(tilesz(1), tilesz(2));
    h.t.TileSpacing = 'loose';
    h.t.Padding = 'compact';

    % Plot index timeseries

    for ir = 1:length(regnum)
        h.ax(ir,1) = nexttile(tnum(ir,1), [1 2]);
        h.ts(ir) = plotsurveyregionindex(Tbl, vplt{iv}, 'col', ir, ...
            'style', 'date_vs_val_annual_and_daily');

        h.ax(ir,2) = nexttile(tnum(ir,3));
        h.doy(ir) = plotsurveyregionindex(Tbl, vplt{iv}, 'col', ir, ...
            'style', 'doy_vs_val_lines');
    end

    % Prettify timeseries

    set([h.ts.lnsummer h.ts.lnfcsummer], 'markersize', 4, 'linewidth', 1.5);
    set(h.ax, 'ylim', V{vplt{iv}, 'limsvyavg'}, 'fontsize', 8, 'box', 'off');
    labelaxes(h.ax(:,1), compose("%s (%s)", reglong', regname'), 'northwestoutsideabove', 'fontweight', 'b');
    arrayfun(@(x) uistack(x, 'top'), [h.ts.lnsummer])

    h.leg(1) = legend([h.ts(1).lndaily, h.ts(1).lnsummer, h.ts(1).lnfc], ...
        ["Hindcast (daily)", "Hindcast (Jul 1)", "Forecast"], ...
        'numcolumns', 2, 'location', 'northeast', 'box', 'off');
    h.leg(1).Position(2) = h.ax(1,1).Position(2)+h.ax(1,1).Position(4);
    h.leg(1).Position(1) = h.ax(1,1).Position(1)+h.ax(1,1).Position(3)-h.leg(1).Position(3);
    
    h.leg(2) = legend(h.doy(1).lndoy(end-3:end), string(2022:2025), ...
        'numcolumns', 2, 'location', 'northwest', 'box', 'off');
    h.leg(2).Position(2) = h.ax(1,2).Position(2)+h.ax(1,2).Position(4);
    h.leg(2).Position(1) = h.ax(1,2).Position(1); 

    % Plot maps

    h.max(1) = nexttile(tnum(1,4), [2 2]);
    h.m(1) = plotmom6akmap(A, MapAnom, ...
        'var', vplt{iv}, 'vartype', 'anomaly', ...
        'mapprops', {'mticks', 'b', 'pticks', 'l'});
    
    h.max(2) = nexttile(tnum(3,4), [2 2]);
    h.m(2) = plotmom6akmap(A, MapFc, ...
        'var', vplt{iv}, 'vartype', 'value', ...
        'mapprops', {'mticks', 'b', 'pticks', 'l'});

    % Prettify and label maps

    set([h.max], 'fontsize', 6, 'box', 'on');
    
    title(h.max(1), {V{vplt{iv}, 'labelname'}, 'Anomaly: Apr 11, 2025'}, 'fontsize', 12);
    title(h.max(2), 'Prediction: Jul 1, 2025', 'fontsize', 12);

    h.m(1).cb.Position(1) = 0.95;
    h.m(2).cb.Position(1) = 0.95;
    set([h.m.cb], 'axislocation', 'out', 'fontsize', 10, 'tickdir', 'out');
end
```

Finally, we performed a cluster analysis across years based on surface and bottom temperature anomalies on Apr 11 of each year.

```{matlab}
%| label: fig-peec25-cluster-allESR
%| fig-cap: Cluster analysis based on surface and bottom temperature on Apr 11 across the three Alaska ESR regions.
%| code-fold: true

[hclus, Cdata] = cluster_on_anomalies(...
    [4 11], ...
    'cpopts', C, ...
    'yr', 1993:2025, ...
    'maskval', [1 3 4], ...
    'ndays', 1, ...
    'verbose', false);
```