% 2025 ESR Workflow, updated
% 
% This is an updated version of the original 2025 ESR workflow, adapted to
% test the newer version of the ak_regional_mom6 code

%% Data processing

%% ... Extract simulation data (run on PPAN)
%
%  First, run ak_esr_peec_extract.sh to get new and/or updated data.
%  Update these variables to match the release details and location of the
%  extracted data.

% Local "CEFI Portal" options

C = cefiportalopts('portalpath', '~/Documents/Data/CEFI/ak_cefiportal', ...
                   'release', 'e202507', ...
                   'subdomain', [0 342 446 743], ...
                   'yyyymmdd', '20240101');

yr = 2025;
esrfol = '~/Documents/Manuscripts/2025_ESR/';

%% ... Create masking variables file

[Scs, Mask] = build_ak_masks(...
    'cpopts', C.setopts('freq','static'), ...
    'expandname', true, ....
    'setuponly', true, ...
    'maskonly', true, ...
    'newname', 'ak_masks');

%% ESR Plots

%% ... Map of bottom temperature, past 20 years

fname = fullfile(esrfol, sprintf('btemp_map_%d-%d', [yr-20+1 yr]));

h = plot_bering_bottom_temp_map_5x4(yr, C);

if ~exist([fname '.png'], 'file')
    export_fig(fname, h.fig, '-png', '-r150', '-nocrop');
end

%% Cluster analysis: July 1 surf/bottom temp anomalies from 6/1-8/22

% 3 primary ESR regions

[hclus(1),Cdata] = cluster_on_anomalies(...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'ndays', 82);

% Bering

hclus(2) = cluster_on_anomalies(...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'maskval', 3, ...
    'Cdata', Cdata, ...
    'ndays', 82);

% Aleutians

hclus(3) = cluster_on_anomalies(...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'maskval', 1, ...
    'Cdata', Cdata, ...
    'ndays', 82);

% Gulf of Alaska

hclus(4) = cluster_on_anomalies(...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'maskval', 4, ...
    'Cdata', Cdata, ...
    'ndays', 82);

masklbls = ["allESR", "BS", "AI", "GOA"];

for ii = 1:4
    fname = fullfile(esrfol, sprintf('clustering_0701-0822_%s',masklbls{ii}));
    if ~exist([fname '.png'], 'file')
        export_fig(fname, hclus(ii).fig, '-png', '-r150');
    end
end

%% ... extra variations

% NBS vs SEBS

hclus(5) = cluster_on_anomalies( ...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'ndays', 82, ...
    'vars', ["tob", "tos"], ...
    'maskvar', "mask_esr_subarea", ...
    'maskval', 3, ...
    'Cdata', Cdata);

hclus(6) = cluster_on_anomalies( ...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'ndays', 82, ...
    'vars', ["tob", "tos"], ...
    'maskvar', "mask_esr_subarea", ...
    'maskval', 4, ...
    'Cdata', Cdata);

% AI, bottom vs surface

hclus(7) = cluster_on_anomalies( ...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'ndays', 82, ...
    'vars', "tob", ...
    'maskvar', "mask_esr_subarea", ...
    'maskval', [1 2 7], ...
    'Cdata', Cdata);
set(hclus(7).ax, 'clim', [-1 1]*0.5)

hclus(8) = cluster_on_anomalies( ...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'ndays', 82, ...
    'vars', "tob", ...
    'maskvar', "mask_survey_area", ...
    'maskval', 52, ...
    'Cdata', Cdata);
set(hclus(8).ax, 'clim', [-1 1]*0.5)

Grd = readcefigridvars(C, ["wet", "mask_esr_area", "mask_survey_area"]);
mask = Grd.wet == 1 & Grd.mask_esr_area == 1 & isnan(Grd.mask_survey_area);

hclus(9) = cluster_on_anomalies( ...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'ndays', 82, ...
    'vars', "tob", ...
    'maskvar', mask, ...
    'Cdata', Cdata);
set(hclus(9).ax, 'clim', [-1 1]*0.5)

hclus(10) = cluster_on_anomalies(...
    [6 1], ...
    'cpopts', C, ...
    'yr', 1993:yr, ...
    'ndays', 82, ...
    'vars', "tos", ...
    'maskvar', "mask_esr_subarea", ...
    'maskval', [1 2 7], ...
    'Cdata', Cdata);

masklbls = ["allESR", "BS", "AI", "GOA",  "NBS", "SEBS", "AItob", "AItobsvy", "AItobdeep", "AItos"];

for ii = 5:10
    fname = fullfile(esrfol, sprintf('clustering_0701-0822_%s',masklbls{ii}));
    if ~exist([fname '.png'], 'file')
        export_fig(fname, h(ii).fig, '-png', '-r150');
    end
end


%% Summary of survey-region temperature stats

regnum = [98 143 52 47]; % EBS, NBS, AI, GOA
regname = ["EBS", "NBS", "AI", "GOA"];

% Variable setup: which ones do we plot?

vplt = ["tob", "tos", "cpool2p0", "cpool0p0"];

% Read surveyavg indices from file

Tbl = readindexdata(C.setopts('subdomain', 'aksvyreg'), ...
    'regnum', regnum, ...
    'vars', vplt);

% Remove leap days from climatology

isleap = month(Tbl.Clim.t) == 2 & day(Tbl.Clim.t) == 29;
Tbl.Clim = Tbl.Clim(~isleap,:);

% Extract July 1 values from each year

Jul1 = structfun(@(x) retime(x, datetime(1993:yr,7,1), 'nearest', 'endvalues', NaN), Tbl, 'uni', 0);

%% Plot time series of index data

V = ak_variable_info;

for ii = 1:length(regnum)
    for iv = 1:length(vplt)
        
        h = plotgrid('size', [1 1], 'mar', 0.08, 'mr', 0.01);
        h.fig.Position(3:4) = [6 4]*72;
        h.fig.Color = 'w';

        h.gobj = plotsurveyregionindex(Tbl, vplt{iv}, 'col', ii, 'year', yr);

        title(h.ax, sprintf('%s: %s', regname(ii), V{vplt{iv},'labelname'}));
        
        fname = fullfile(esrfol, sprintf('timeseries_%s_%s',regname{ii}, vplt{iv}));

        if ~exist([fname '.png'], 'file')
            export_fig(fname, h.fig, '-png', '-r150', '-nocrop');
        end
        close(h.fig);
    end
end
